#version: '3.1'
#
#services:
#  db:
#    image: mariadb:10.4 # ?? ???? ??
#    container_name: team2_project
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: team2_project
#    ports:
#      - "3309:3306"

#--- 아래 부분 사용하면 됨
#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: "jdbc:mariadb://127.0.0.1:3309/kosta24"
#    username: "root"
#    password: "tkdals1234"
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect

